{
 "title": "League Stats",
 "time": { "from": "now-3d", "to": "now" },
 "templating": {
  "list": [
   { "name": "SIDE", "label": "Red or Blue", "query": "Red : RED, Blue : BLUE" },
   {
    "name": "LANE",
    "label": "Lane",
    "query": "Top : TOP, Jungle : JUNGLE, Middle : MIDDLE, Bottom : BOTTOM"
   },
   {
    "name": "ROLE",
    "label": "Role",
    "query": "SELECT\n    participants.role\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\nGROUP BY participants.role;"
   },
   {
    "name": "CHAMPION",
    "label": "Champion",
    "query": "SELECT\n    champions.name\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\nGROUP BY\n    champions.champion_id;\n"
   },
   {
    "name": "SUMMONER_NAME",
    "label": "Summoner",
    "query": "SELECT participants.summoner_name\nFROM participants\nGROUP BY participants.summoner_name\nORDER BY count(*) desc\nLIMIT 1"
   }
  ]
 },
 "panels": [
  { "title": "Cumulative", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OP Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.summoner_name AS 'Summoner',\n    10-participants.op_score_rank AS 'Op Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n    champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\nORDER BY \n    games.created_at ASC",
     "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.summoner_name AS 'Summoner',\n    10-participants.op_score_rank AS 'Op Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n    champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\nORDER BY \n    games.created_at ASC",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Vision Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.vision_score AS 'Vision Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\nORDER BY \n    games.created_at ASC",
     "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.vision_score AS 'Vision Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\nORDER BY \n    games.created_at ASC",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Lane Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.lane_score AS 'Lane Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\nORDER BY \n    games.created_at ASC",
     "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.lane_score AS 'Lane Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\nORDER BY \n    games.created_at ASC",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "By Side",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "OP Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.team_key AS 'Side',\n    10-participants.op_score_rank AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.team_key IN ('RED','BLUE')\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.team_key AS 'Side',\n    10-participants.op_score_rank AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.team_key IN (${SIDE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    },
    {
     "title": "Vision Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.team_key AS 'Side',\n    participants.vision_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.team_key IN (${SIDE:singlequote})\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.team_key AS 'Side',\n    participants.vision_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.team_key IN (${SIDE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    },
    {
     "title": "Lane Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.team_key AS 'Side',\n    participants.lane_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.team_key IN (${SIDE:singlequote})\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.team_key AS 'Side',\n    participants.lane_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.team_key IN (${SIDE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    }
   ]
  },
  {
   "title": "By Lane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "OP Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.position AS 'Lane',\n    10-participants.op_score_rank AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.position IN ('TOP','JUNGLE','MIDDLE','BOTTOM')\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.position AS 'Lane',\n    10-participants.op_score_rank AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.position IN (${LANE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    },
    {
     "title": "Vision Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.position AS 'Lane',\n    participants.vision_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.position IN (${LANE:singlequote})\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.position AS 'Lane',\n    participants.vision_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.position IN (${LANE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    },
    {
     "title": "Lane Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.position AS 'Lane',\n    participants.lane_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.position IN (${LANE:singlequote})\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.position AS 'Lane',\n    participants.lane_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.position IN (${LANE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    }
   ]
  },
  {
   "title": "By Role",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "OP Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.role AS 'Role',\n    10-participants.op_score_rank AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.role IN ('MAGE','TANK')\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.role AS 'Role',\n    10-participants.op_score_rank AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.role IN (${ROLE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    },
    {
     "title": "Vision Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.role AS 'Role',\n    participants.vision_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.role IN (${ROLE:singlequote})\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.role AS 'Role',\n    participants.vision_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.role IN (${ROLE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    },
    {
     "title": "Lane Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    participants.role AS 'Role',\n    participants.lane_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.role IN (${ROLE:singlequote})\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    participants.role AS 'Role',\n    participants.lane_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND participants.role IN (${ROLE:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    }
   ]
  },
  {
   "title": "By Champion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "OP Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    champions.name AS 'Champion',\n    10-participants.op_score_rank AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND champions.name IN ('Volibear','Teemo','Ekko')\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    champions.name AS 'Champion',\n    10-participants.op_score_rank AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND champions.name IN (${CHAMPION:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    },
    {
     "title": "Vision Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    champions.name AS 'Champion',\n    participants.vision_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND champions.name IN (${CHAMPION:singlequote})\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    champions.name AS 'Champion',\n    participants.vision_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND champions.name IN (${CHAMPION:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    },
    {
     "title": "Lane Score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
     "targets": [
      {
       "queryText": "SELECT\n    games.created_at AS 'time',\n    champions.name AS 'Champion',\n    participants.lane_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND champions.name IN (${CHAMPION:singlequote})\nORDER BY \n    games.created_at ASC",
       "rawQueryText": "SELECT\n    games.created_at AS 'time',\n    champions.name AS 'Champion',\n    participants.lane_score AS 'Score'\nFROM\n    participants\nJOIN\n    games ON participants.game_id = games.game_id\nJOIN\n        champions ON participants.champion_id = champions.champion_id\nWHERE participants.summoner_name IN (${SUMMONER_NAME:singlequote})\n    AND champions.name IN (${CHAMPION:singlequote})\nORDER BY \n    games.created_at ASC",
       "timeColumns": [ "time" ]
      }
     ]
    }
   ]
  }
 ]
}