services:
  opggvisualizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opggvisualizer
    environment:
      - SUMMONER_ID=${SUMMONER_ID}
      - DATABASE_PATH=${DATABASE_PATH}
    volumes:
      - opgg_data:/opggvisualizer_data
    ports:
      - "8080:8080" # API server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - opgg_data:/opggvisualizer_data:ro # Mount the same data volume as read-only
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000" # Grafana UI
    depends_on:
      - opggvisualizer
    restart: unless-stopped

  cron:
    image: alpine:latest
    container_name: cron
    depends_on:
      - opggvisualizer
    volumes:
      - opgg_data:/opggvisualizer_data
    command: >
      /bin/sh -c "
      echo '0 * * * * wget --post-data "foo=bar" --quiet --output-document=- http://opggvisualizer:8080/refresh' | crontab - &&
      crond -f"
    restart: unless-stopped

volumes:
  opgg_data:
    driver: local
  grafana_data:
    driver: local
